### ISSUE TITLE
fails with h5py 3

### ISSUE THREAD

**Issue by drew-parsons** [hydroffice/hyo2_bagexplorer#1]
bag explorer needs to be updated to work with h5py 3.

h5py changed the way the file mode is set when accessing .h5 files.  The mode now needs to be given explicitly.

Test logs report
```
.EEE.....
======================================================================
ERROR: test_bag_File_filename (test_hydroffice_bag_base.TestBagBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.niorsqvb/downtmp/autopkgtest_tmp/tests/test_hydroffice_bag_base.py", line 34, in test_bag_File_filename
    bag_0 = File(self.file_bag_0)
  File "/usr/lib/python3/dist-packages/hydroffice/bag/base.py", line 69, in __init__
    super(File, self).__init__(name=name, mode=mode, driver=driver,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 215, in make_fid
    raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")
ValueError: Invalid mode; must be one of r, r+, w, w-, x, a

======================================================================
ERROR: test_bag_File_open (test_hydroffice_bag_base.TestBagBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.niorsqvb/downtmp/autopkgtest_tmp/tests/test_hydroffice_bag_base.py", line 30, in test_bag_File_open
    self.assertIsNotNone(File(self.file_bag_0))
  File "/usr/lib/python3/dist-packages/hydroffice/bag/base.py", line 69, in __init__
    super(File, self).__init__(name=name, mode=mode, driver=driver,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 215, in make_fid
    raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")
ValueError: Invalid mode; must be one of r, r+, w, w-, x, a

======================================================================
ERROR: test_bag_File_raise (test_hydroffice_bag_base.TestBagBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.niorsqvb/downtmp/autopkgtest_tmp/tests/test_hydroffice_bag_base.py", line 27, in test_bag_File_raise
    File(self.file_fake_0)
  File "/usr/lib/python3/dist-packages/hydroffice/bag/base.py", line 69, in __init__
    super(File, self).__init__(name=name, mode=mode, driver=driver,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/files.py", line 215, in make_fid
    raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")
ValueError: Invalid mode; must be one of r, r+, w, w-, x, a

----------------------------------------------------------------------
Ran 9 tests in 0.003s

FAILED (errors=3)
```

full log https://ci.debian.net/data/autopkgtest/testing/amd64/h/hydroffice.bag/14823832/log.gz ,

**Comment by drew-parsons** [comment]
bug transferred to https://github.com/hydroffice/hyo_bag/issues/3
